name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run iceberg-rust-spec tests
      run: cargo test -p iceberg-rust-spec --lib --verbose
    - name: Run iceberg-rust tests
      run: cargo test -p iceberg-rust --lib --verbose
    - name: Run datafusion-iceberg tests
      run: cargo test -p datafusion_iceberg --tests --verbose -j 2

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Clippy
      run: rustup component add clippy
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
