[package]
name = "iceberg-sql-catalog"
version = "0.8.0"
edition = "2021"

description = "Sql catalog for the unofficial Iceberg table format implementation"

license = "Apache-2.0"

repository = "https://github.com/JanKaul/iceberg-rust"

[features]
default = ["runtime-tokio"]
runtime-tokio = ["sqlx/runtime-tokio"]
runtime-async-std = ["sqlx/runtime-async-std"]

[dependencies]
async-trait.workspace = true
futures.workspace = true
iceberg-rust = { path = "../../iceberg-rust", version = "0.8.0" }
object_store.workspace = true
serde_json.workspace = true
sqlx = { version = "0.8", features = ["tls-rustls", "any", "sqlite", "postgres", "mysql"], default-features = false }
thiserror.workspace = true
url.workspace = true
uuid = { version = "1.13.2", features = ["v4"] }

[dev-dependencies]
datafusion.workspace = true
datafusion_iceberg = { path = "../../datafusion_iceberg", version = "0.8.0" }
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "any", "sqlite", "postgres", "mysql"], default-features = false }
testcontainers = "0.23"
testcontainers-modules = { version = "0.11", features = ["localstack", "postgres"] }
tokio = "1"
